apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmkms-pvc
  labels:
    {{- include "tmkms.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: tmkms-local-storage
  resources:
    requests:
      storage: {{ $.Values.tmkms_local_storage.capacity }}
