apiVersion: v1
kind: Secret
metadata:
  name: tmkms-instance-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tmkms.labels" . | nindent 4 }}
type: "Opaque"
data:
  kms-identity.key: {{ .Values.validator.nodeKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tmkms-validator-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tmkms.labels" . | nindent 4 }}
type: "Opaque"
data:
  consensus.key: {{ .Values.validator.privKey }}
