apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tmkms-local-storage
  labels:
    {{- include "tmkms.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
